name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Hello1
      run: rm .npmrc && echo 'https://npm.pkg.github.com/:_authToken={{secrets.GITHUB_TOKEN}}' > .npmrc
    - name: Hello2
      run: npm install
    - name: AWS Lambda Deploy
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: gorush
        publish: true
        # dry_run: true
        # zip_file: output.zip
      