name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploying
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Hello1
      run: rm .npmrc && echo 'https://npm.pkg.github.com/:_authToken={{secrets.GITHUB_TOKEN}}' > .npmrc
    - name: Hello2
      run: npm install
      